export default {
  id: "AURORA",
  name: "Aurora",
  version: "1.0.0",
  engine: "4.0",
  author: "CVify",
  description: "Add a description for your theme here.",
  thumbnail: "./preview.webp",
  supportedModes: ["dark"],
  defaultPreset: "AURORA",
  features: {
    github: true,
    analytics: true,
    resume: true,
    contact: true,
    particles: false,
    glass: false,
  },
  navigation: {
    home: "hero",
    about: "about",
    journey: "experience",
    showcase: "showcase",
    contact: "contact",
  },
};
