/**
 * Comprehensive list of disposable / temporary email service domains.
 * Mirroring the backend list to provide immediate client-side feedback.
 *
 * Sources:
 * - https://github.com/disposable-email-domains/disposable-email-domains
 * - https://github.com/ivolo/disposable-email-domains
 * - Manual additions based on observed abuse patterns
 *
 * Last updated: 2026-03-22
 */
const blockedDomains = new Set([
  // ─── Mailinator Family ───────────────────────────────────────────────────
  "mailinator.com",
  "mailinator2.com",
  "mailinator.net",
  "mailinatar.com",
  "mailinater.com",
  "mailinator.org",
  "mailinator.us",
  "mailinator.info",
  "mailinator.co.uk",

  // ─── Guerrilla Mail Family ───────────────────────────────────────────────
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.info",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamailblock.com",
  "grr.la",
  "spam.la",
  "sharklasers.com",
  "guerrillamailblock.com",
  "spam4.me",

  // ─── YopMail Family ──────────────────────────────────────────────────────
  "yopmail.com",
  "yopmail.fr",
  "cool.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",
  "courriel.fr.nf",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",

  // ─── Temp-Mail.org Family ────────────────────────────────────────────────
  "temp-mail.org",
  "temp-mail.ru",
  "temp-mail.io",
  "temp-mail.net",
  "tempmail.com",
  "tempmail.net",
  "tempmail.org",
  "tempmail.de",
  "tempmail.io",
  "tempmail.us",
  "tempmail.co",
  "tempmail.plus",
  "tempr.email",
  "tempemail.net",
  "tempymail.com",
  "tempalias.com",
  "tempinbox.com",
  "tempinbox.co.uk",
  // netoiu.com and temp-mail.org subdomains
  "netoiu.com",
  "vomoto.com",
  "rfcdrive.com",
  "merepost.com",

  // ─── 10MinuteMail / QuickEmail ───────────────────────────────────────────
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemail.de",
  "10minutemail.eu",
  "10minutemail.us",
  "10minutemail.co.uk",
  "10minutemail.info",
  "10minutemail.be",
  "10minutemail.nl",
  "10minutemail.pl",
  "10minutemail.pro",
  "10minutemail.ru",
  "10minutemail.ga",
  "10mails.net",
  "10minmail.de",
  "minutemailbox.com",

  // ─── TrashMail Family ────────────────────────────────────────────────────
  "trashmail.me",
  "trashmail.at",
  "trashmail.com",
  "trashmail.io",
  "trashmail.net",
  "trashmail.org",
  "trashmail.de",
  "trashmail.xyz",

  // ─── Dispostable / Discard ───────────────────────────────────────────────
  "dispostable.com",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "disposablemail.com",
  "disposable.com",

  // ─── Throwaway ───────────────────────────────────────────────────────────
  "throwam.com",
  "throwtempmail.com",
  "throwme.com",
  "throwaway.email",
  "throwam.com",

  // ─── Fake / Spam Oriented ────────────────────────────────────────────────
  "fakemail.net",
  "fakeinbox.com",
  "fake-email.com",
  "fakemailgenerator.com",
  "mailnull.com",
  "mailnesia.com",
  "maildrop.cc",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamfree24.org",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree.eu",
  "spam.me",
  "spoofmail.de",
  "sogetthis.com",
  "spamhereplease.com",
  "spam.care",
  "spamcon.org",
  "spamdecoy.net",
  "spamex.com",
  "spamgoes.in",
  "spamhole.com",
  "spamify.com",
  "spamspot.com",
  "spamthis.co.uk",
  "spamtroll.net",

  // ─── Mailmoat / Mailnull ─────────────────────────────────────────────────
  "mailmoat.com",
  "mailnull.com",
  "mailnesia.com",

  // ─── GetNada / Nada ──────────────────────────────────────────────────────
  "getnada.com",
  "nadet.com",

  // ─── Mohmal ──────────────────────────────────────────────────────────────
  "mohmal.com",
  "mohmal.in",
  "mohmal.it",
  "mohmal.net",
  "mohmal.im",

  // ─── Mailtemp / Tempmailaddress ──────────────────────────────────────────
  "mailtemp.info",
  "tempmailaddress.com",
  "emailtemporario.com.br",
  "mailtemp.de",
  "mail-temporaire.fr",
  "emailtemporar.ro",

  // ─── Crazymailing / Yournewid ────────────────────────────────────────────
  "crazymailing.com",
  "yournewid.com",

  // ─── Mailbox.in.ua / throwam ─────────────────────────────────────────────
  "mailbox.in.ua",
  "getairmail.com",
  "filzmail.com",
  "owlpic.com",

  // ─── Wegwerfmail ─────────────────────────────────────────────────────────
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wegwerfmail.info",

  // ─── Jetable ─────────────────────────────────────────────────────────────
  "jetable.com",
  "jetable.net",
  "jetable.org",
  "jetable.fr.nf",

  // ─── E4Ward / Nwldx ──────────────────────────────────────────────────────
  "e4ward.com",
  "nwldx.com",
  "nowmymail.com",

  // ─── Emailondeck ─────────────────────────────────────────────────────────
  "emailondeck.com",
  "emailondeck.net",

  // ─── Mytemp / TempmailGen ────────────────────────────────────────────────
  "mytemp.email",
  "tempmailgen.com",

  // ─── Various Single-Use Services ─────────────────────────────────────────
  "emkei.cz",
  "einrot.com",
  "einrot.de",
  "kurzepost.de",
  "objectmail.com",
  "obobbo.com",
  "proxymail.eu",
  "rcpt.at",
  "rfc822.org",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safetypost.de",
  "nowmymail.com",
  "spamevader.net",
  "haltospam.com",
  "bspamfree.org",
  "bugmenot.com",
  "easytrashmail.com",
  "notsharingmy.info",
  "zetmail.com",
  "no-spam.ws",
  "vidchart.com",
  "viditag.com",
  "veryrealemail.com",
  "urhen.com",
  "uggsrock.com",
  "trbvm.com",
  "thisisnotmyrealemail.com",
  "thanksnospam.info",
  "wh4f.org",
  "whatiaas.com",
  "whatifapp.com",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.net",
  "zomg.info",

  // ─── Nospam / Spamgourmet ────────────────────────────────────────────────
  "nospam4.us",
  "nobulk.com",
  "nodispo.com",

  // ─── Popular burner services 2024-2025 ───────────────────────────────────
  "tempmail.lol",
  "burnermail.io",
  "easymail.top",
  "minute.email",
  "tmail.com",
  "tmail.io",
  "tmail.ws",
  "inboxkitten.com",
  "mailsac.com",
  "mailslurp.com",
  "guerrillamail.org",
  "getairmail.net",
  "anonaddy.com",
  "simplelogin.io",
  "33mail.com",
  "spamgourmet.com",
  "meltmail.com",
  "yopmail.net",
  "yopmail.org",
  "mailnull.net",
  "mailnull.org",
  "maillinator.com",
  "throwam.io",
  "throwam.net",
  "mailparser.io",
  "tempmail.email",
  "tmpmail.net",
  "tmpmail.org",
  "tmpmail.io",
  "email-jetable.fr",

  // ─── Pakistani/Regional Disposable Domains ───────────────────────────────
  "vipemail.net",
  "emeil.in",
  "emeil.ir",

  // ─── Recently seen abuser domains ────────────────────────────────────────
  "netoiu.com", // observed in DB abuse
  "vomoto.com", // temp-mail.org subdomain service
  "rfcdrive.com", // temp-mail.org subdomain service
  "merepost.com", // temp-mail.org subdomain service
  "oosnd.com",
  "inboxstore.me",
  "amilegit.com",
  "amiri.net",
  "spamoff.de",
  "mail4trash.com",
  "trash-mail.at",
  "trashmail.ws",
  "trashmail.xyz",
  "trashmail.win",
  "tempmail.ninja",
  "trash-me.com",
  "rmqkr.net",
  "pjjkp.com",
  "killmail.com",
  "killmail.net",
  "fakeinbox.cf",
  "mt2014.com",
  "mt2015.com",
  "nospamfor.us",
  "cuvox.de",
  "dayrep.com",
  "eintagsmail.de",
  "fleckens.hu",
  "guam.net",
  "iroid.com",
  "krovatka.su",
  "lroid.com",
  "mailexpire.com",
  "mailfall.com",
  "mailn.de",
  "mailnew.com",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailslite.com",
  "nospamforus.com",
  "punkass.com",
  "putthisinyourgps.com",
  "qisdo.com",
  "qisoa.com",
  "rejectmail.com",
  "rklips.com",
  "rppkn.com",
  "runobjrfs.com",
  "scatmail.com",
  "servermaps.net",
  "shitaway.com",
  "sinaite.net",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slopsbox.com",
  "slutty.com",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakmail.de",
  "sofort-mail.de",
  "spam-be-gone.com",
  "tempr.email",
  "testudine.com",
  "thankyou2010.com",
  "tittbit.in",
  "turual.com",
  "umail.net",
  "super-auswahl.de",
  "vpn.st",
  "wazabi.club",
  "winemaven.info",
  "yep.it",
  "za.com",
  "zippymail.info",
  "zain.site",
  "tinyurl.com",
  "tempalias.org",
  "tempemail.biz",
  "tempemail.co.za",
  "tempemail.com",
  "emailisvalid.com",
  "emaildrop.io",
  "emailfake.com",
  "emailfake.ml",
  "emailinfive.com",
  "emailigo.de",
  "emailisvalid.com",
  "meinspamschutz.de",
  "meltmail.com",
  
  // ─── Recently Observed Abuser Domains (2026) ─────────────────────────────
  "paylaar.com",
  "moakt.com",
  "moakt.co",
  "moakt.org",
  "feelingion.com",
  "competirer.com",
  "gfbysaints.com",
  "broothi.com",
  "cablegateast.com",
  "tachnuqia.com",
  "btintinternet.com",
  "mailstore.keyworddo.com",
  "ruincuit.com",
  "tmarapten.com",
  "flowersth.com",
  "snakement.com",
  "knowond.com",
  "temporarymail.com",
  "mail.tm",
  "smailpro.com",
  "tempinbox.xyz",
  "mailporary.com",
  "maildax.com",
  "tmailor.com",
  "evapmail.com",
  "mailticking.com",
  "emailnator.com",
  "inboxes.com",
  "mailwave.dev",
  "boomlify.com",
  "tempmailo.com",
  "throwawaymail.com",
  "disposable-mail.com",
  "dropmail.me",
  "1secmail.com",
  "cybertemp.xyz",
  "tmail.delivery",
  "m.kuku.lu",
  "priyo.email",
  "mainnetmail.com",
  "mail-temp.site",
  "trashmailr.com",
  "muellmail.com",
  "tempmail.id.vn",
  "mailscr.us",
  "edumailfree.com",
  "vsmailpro.com",
  "noopmail.org",
  "tempmail.tel",
  "tempm.com",
  "generator.email",
  "mail-temp.com",
  "mail-fake.com",
  "plingest.com",
  "mail7.io",
  "1secmail.net",
  "1secmail.org",
  "tempemail.cc",
  "bulc.club",
  "addy.io",
  "10minutenmail.xyz",
  "24hinbox.com",
  "10mail.org",
]);

/**
 * Returns true if the email's domain is a known disposable service.
 * Also checks subdomains (e.g. user@subdomain.mailinator.com)
 * @param {string} email
 * @returns {boolean}
 */
export const isDisposableEmail = (email) => {
  if (!email || !email.includes("@")) return false;

  const domain = email.split("@")[1].toLowerCase().trim();

  // Direct match or subdomain match
  for (const blocked of blockedDomains) {
    if (domain === blocked || domain.endsWith("." + blocked)) {
      return true;
    }
  }

  return false;
};

export default blockedDomains;
